name: Check codestyle with wemake-python-styleguide

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: wemake-services/wemake-python-styleguide@master
      with:
        reporter: 'github-pr-review'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
